### ISSUE TITLE
There was a problem when I ran train.py. Can you see why? Thank you

### ISSUE THREAD

**Issue by lemonqing** [oddguan/audio_visual_video_caption#1]
return torch.stack(batch,0,out=out)
invalid argument 0: sizes of tensors must match except in dimension 0.Got 640 and 16 in dimension 1....

**Comment by oddguan** [comment]
Did preprocessing scripts run fine? Can you post the whole error log?

**Comment by lemonqing** [comment]
The preprocessing script is working properly，I get video.npy and audio.npy.
<img width="556" alt="_20181121144528" src="https://user-images.githubusercontent.com/45202299/48823531-1ce12b80-ed9c-11e8-89e5-40c9b977b9ae.png">

**Comment by oddguan** [comment]
It seems like each video that the dataloader loaded has different dimension... I haven't run my model for a long time now and I thought it worked fine when I ran it several months ago. I'll re-run it when I have the time to see if I can reproduce this issue. Sorry about it.

**Comment by oddguan** [comment]
By the way, what is the batch size you used for training?

**Comment by lemonqing** [comment]
Thank you, please, maybe you can give me your data set, is it because I found the data set has a problem, some video have no audio features.My training batch size is 128.

**Comment by lemonqing** [comment]
now ,i have the new question

![_20181123135818](https://user-images.githubusercontent.com/45202299/48929942-02d45400-ef28-11e8-8bad-7c502346332e.jpg)

**Comment by oddguan** [comment]
Sorry for replying you late... I was traveling for Thanksgiving and wasn't able to answer your questions. The dataset I used can be found right [here](https://drive.google.com/file/d/1Qi6Gn_l93SzrvmKQQu-drI90L-x8B0ly/view). But, it shouldn't be a problem if the video does not have a sound for my model because I used zero paddings as the audio input if a video has no sound. 

For the next question, I have never encountered this problem and when I was googling online, seems like people resolved the problem by rebooting the computer... Maybe try that and see if it works? 

I still haven't had a chance to rerun my model, but I will do it tomorrow probably.

**Comment by oddguan** [comment]
Or maybe try [this](https://discuss.pytorch.org/t/cuda-runtime-error-30/19287)?

**Comment by lemonqing** [comment]
Thank you very much. Have a nice trip. I will read the blog.

**Comment by rohan1561** [comment]
Hey, has the dataset been taken down? Where can I get it then? I have looked..
